# Generated by Django 3.2.4 on 2021-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_ID', models.IntegerField()),
                ('exception_name', models.CharField(max_length=50)),
                ('exception_component', models.CharField(max_length=20)),
                ('exception_level', models.CharField(max_length=20)),
                ('exception_description', models.CharField(max_length=50)),
                ('cob_dt', models.DateField()),
                ('business_line', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('profit_center', models.CharField(max_length=20)),
                ('legal_entity', models.CharField(max_length=20)),
            ],
        ),
    ]
