# Generated by Django 3.2.4 on 2021-07-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exceptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceptiontype',
            name='cob_dt',
        ),
    ]
