# Generated by Django 3.2.4 on 2021-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exceptions', '0003_exceptiontype_cob_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptiontype',
            name='book_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
