# Generated by Django 3.2.4 on 2021-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd_amount_type',
            name='BUSINESS_LINE_ID',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sd_feed_validation',
            name='CATALOG_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sd_feed_validation',
            name='HIERARCHY_FEED_ID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sd_feed_validation',
            name='PARENT_ID',
            field=models.IntegerField(null=True),
        ),
    ]
