# Generated by Django 3.2.5 on 2021-07-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSource', '0002_auto_20210704_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd_amount_type',
            name='BUSINESS_LINE_ID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sd_feed_validation',
            name='CATALOG_ID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sd_feed_validation',
            name='HIERARCHY_FEED_ID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sd_feed_validation',
            name='PARENT_ID',
            field=models.IntegerField(blank=True),
        ),
    ]
