# Generated by Django 3.2.5 on 2021-07-02 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSource', '0002_auto_20210701_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exceptionID', models.IntegerField(unique=True)),
                ('exception_name', models.CharField(max_length=50)),
                ('exception_description', models.CharField(max_length=200)),
                ('exception_function', models.CharField(max_length=50)),
                ('exception_component', models.CharField(choices=[('TAInbound', 'TAInbound'), ('TAI', 'TAI'), ('Accounting', 'Accounting')], max_length=20)),
                ('exception_level', models.CharField(choices=[('HIGH', 'HIGH'), ('LOW', 'LOW')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 10, 6, 15, 339572), null=True),
        ),
    ]
