# Generated by Django 3.2.5 on 2021-07-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSource', '0003_auto_20210705_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sd_feed_validation',
            name='CATALOG_ID',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
