# Generated by Django 3.2.5 on 2021-07-02 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSource', '0003_auto_20210702_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exception',
            new_name='ExceptionType',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 10, 7, 40, 58560), null=True),
        ),
    ]
