# Generated by Django 3.2.5 on 2021-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSource', '0004_alter_sd_feed_validation_catalog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='filterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ID', models.IntegerField(blank=True)),
                ('exception_name', models.CharField(blank=True, choices=[('requiredFieldEmpty', 'requiredFieldEmpty'), ('dataProvision', 'dataProvision'), ('scopeGap', 'scopeGap'), ('misc', 'misc'), ('rulesOtherwise', 'rulesOtherwise'), ('DuplicatedVersionFound', 'DuplicatedVersionFound'), ('wrongQuantityGrossNet', 'wrongQuantityGrossNet'), ('holidayValueDate', 'holidayValueDate'), ('noRiskMgmtView', 'noRiskMgmtView'), ('recDiffView', 'recDiffView'), ('noSettlementView', 'noSettlementView'), ('optionalFieldEmpty', 'optionalFieldEmpty'), ('netGrossDifference', 'netGrossDifference'), ('zeroProof', 'zeroProof'), ('notValidField', 'notValidField'), ('defaultValue', 'defaultValue'), ('notValidField', 'notValidField')], max_length=50)),
                ('exception_layer', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
